server:
  port: 8081

spring:
  resources:
    static-locations: classpath:/static/,classpath:/resources/,classpath:/public/
#  devtools:
#    restart:
#      exclude: static/**, public/**, resources/**
